project_id = "ulyhwvbzahknamgalzud"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"

[functions.bravive-pix-create]
verify_jwt = false

[functions.bravive-pix-status]
verify_jwt = false

[functions.zyropay-pix-create]
verify_jwt = false

[functions.zyropay-pix-status]
verify_jwt = false

[functions.zyropay-webhook]
verify_jwt = false

[functions.mangofy-pix-create]
verify_jwt = false

[functions.mangofy-pix-status]
verify_jwt = false

[functions.mangofy-webhook]
verify_jwt = false
